# Generated by Django 4.1.5 on 2023-01-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Home product name')),
                ('aabout', models.TextField(verbose_name='Home product about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Home product image')),
                ('price', models.ImageField(upload_to='', verbose_name='Home product price')),
            ],
            options={
                'verbose_name': 'HomeProduct',
                'verbose_name_plural': 'HomeProducts',
            },
        ),
    ]
