# Generated by Django 4.1.5 on 2023-01-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homeproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Homeabout name')),
                ('name1', models.CharField(max_length=100, verbose_name='Homeabout name1')),
                ('name2', models.CharField(max_length=1000, verbose_name='Homeabout name2')),
                ('name3', models.CharField(max_length=100, verbose_name='Homeabout name3')),
                ('name4', models.CharField(max_length=100, verbose_name='Homeabout name4')),
                ('name5', models.CharField(max_length=100, verbose_name='Homeabout name5')),
                ('name6', models.CharField(max_length=100, verbose_name='Homeabout name6')),
                ('name7', models.CharField(max_length=100, verbose_name='Homeabout name7')),
                ('name8', models.CharField(max_length=100, verbose_name='Homeabout name8')),
                ('img', models.ImageField(upload_to='media', verbose_name='Homeabout image')),
            ],
        ),
        migrations.AlterField(
            model_name='homeproducts',
            name='price',
            field=models.IntegerField(verbose_name='Home product price'),
        ),
    ]
