# Generated by Django 4.1.5 on 2023-02-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ourproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='aboutour name')),
                ('name1', models.CharField(max_length=30, verbose_name='aboutour name1')),
                ('about', models.TextField(verbose_name='aboutour about')),
                ('img', models.ImageField(upload_to='media', verbose_name='aboutour image')),
            ],
            options={
                'verbose_name': 'AboutOur',
                'verbose_name_plural': 'AboutOur',
            },
        ),
        migrations.AlterModelOptions(
            name='ourproducts',
            options={'verbose_name': 'OurProducts', 'verbose_name_plural': 'OurProducts'},
        ),
    ]
