# Generated by Django 4.1.5 on 2023-02-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutour_alter_ourproducts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='aboutteam name')),
                ('name1', models.CharField(max_length=30, verbose_name='abouteam name1')),
                ('about', models.TextField(verbose_name='aboutteam about')),
                ('img', models.ImageField(upload_to='media', verbose_name='abouteam image')),
            ],
        ),
    ]
