# Generated by Django 4.1.5 on 2023-02-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_abouthappy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='aboutpart image')),
            ],
        ),
    ]
